services:
    - type: web
      name: etran-maney-transfers
      repo: https://github.com/etran/etran-maney-transfers
      env: docker
      dockerfilePath: ./Dockerfile
      plan: free
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_KEY
            value: base64:your-key
          - key: DB_CONNECTION
            value: mysql
          - key: DB_HOST
            value: your-db-host
          - key: DB_PORT
            value: 3306
          - key: DB_DATABASE
            value: your-db
          - key: DB_USERNAME
            value: your-user
          - key: DB_PASSWORD
            value: your-pass
