services:
    - type: web
      name: etran-maney-transfers
      env: docker
      plan: free
      dockerfilePath: ./Dockerfile
      autoDeploy: true
      envVars:
          - key: APP_NAME
            value: Laravel
          - key: APP_ENV
            value: production
          - key: APP_KEY
            value: base64:U6VWDbbXlCuLRKGJVc5EXoVOf5FYEvt/qNVgBy2RAuY=
          - key: APP_DEBUG
            value: 'false'
          - key: APP_URL
            value: https://etran-maney-transfers.onrender.com
          - key: LOG_CHANNEL
            value: stack
          - key: LOG_LEVEL
            value: debug

          # Database config (example)
          - key: DB_CONNECTION
            value: mysql
          - key: DB_HOST
            value: your-database-host
          - key: DB_PORT
            value: 3306
          - key: DB_DATABASE
            value: etran_maney_transfers
          - key: DB_USERNAME
            value: your-db-user
          - key: DB_PASSWORD
            value: your-db-pass

          # Session/Cache/Queue
          - key: SESSION_DRIVER
            value: database
          - key: QUEUE_CONNECTION
            value: database
          - key: CACHE_STORE
            value: database

          # Redis (optional — if used)
          - key: REDIS_CLIENT
            value: phpredis
          - key: REDIS_HOST
            value: 127.0.0.1
          - key: REDIS_PORT
            value: 6379

          # Mail
          - key: MAIL_MAILER
            value: log
          - key: MAIL_HOST
            value: 127.0.0.1
          - key: MAIL_PORT
            value: 2525
          - key: MAIL_FROM_ADDRESS
            value: hello@example.com
          - key: MAIL_FROM_NAME
            value: Laravel

          # Vite (optional)
          - key: VITE_APP_NAME
            value: Laravel
