services:
    - type: web
      name: etran-maney-transfers
      env: docker
      plan: free
      dockerfilePath: ./Dockerfile
      autoDeploy: true
      branch: main
      buildFilter:
          paths:
              - '**/*'
      envVars:
          - key: APP_NAME
            value: Laravel
          - key: APP_ENV
            value: production
          - key: APP_KEY
            value: base64:U6VWDbbXlCuLRKGJVc5EXoVOf5FYEvt/qNVgBy2RAuY=
          - key: APP_DEBUG
            value: false
          - key: APP_URL
            value: https://etran-maney-transfers.onrender.com

          # Database (replace with your actual DB credentials)
          - key: DB_CONNECTION
            value: mysql
          - key: DB_HOST
            value: your-db-host.render.com
          - key: DB_PORT
            value: 3306
          - key: DB_DATABASE
            value: etran_maney_transfers
          - key: DB_USERNAME
            value: your-db-username
          - key: DB_PASSWORD
            value: your-db-password

          - key: LOG_CHANNEL
            value: stack
          - key: CACHE_STORE
            value: database
          - key: SESSION_DRIVER
            value: database
          - key: QUEUE_CONNECTION
            value: database
          - key: VITE_APP_NAME
            value: Laravel
